language: node_js
node_js:
- stable
before_script:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: cjLdOwy9wnw1r92xntUY2XNloD3JNO/yj3HNnPo9jNGTGE8Ld0i4pANIgUczD62aicS0EtcCGWwVBtTJUugr61+TSsWjJLszC7oxPzrwXu8saetk+IwywCkgHeHYIwJ+nzhrl39xUbx6gNJxLe4MWlQOBxRATaFdVOwBkZzSUxmKKDU5bCOlLqzrRDMCmxXUCDnticY4ETQVprbyNG6NrYEdfCOEivcHjtvNYuPJcZpy3lXv81SVzq6QmxF620yFhh6SkglR/AaXJSrgHWUF2uQe0dYEFMmHkHa6pDmKA0YYA/DXeKDw2sdJ9SX5OQcJw+WvDVR8ebSaS5oPHZiFlVanhfbSUVohZnrRi+IUAceMxeozffsv2GyvRscEF5M+CpPNW9AidPFEViz3Do9m5lBIuhQjOuY2gZYaifvVch/eqpWxP0Q6TKotrHSfneW5pxDFP0yw59s3avE2xvoUpm1GC0oIfqB0aQ1IKeRvFXkUO1WF1gcHP//oIkhAvhwMepadyXfvKlZrFdKxRfR1mB53YGGL1stOnU98ZNHklFD5BCsqd1u2NhtfarOmnts6ykQIus+qoi1sbfbJ9IytaYgLWuQETBlXLCgzJLqLyb9jjmbGdOlvjVjLn36gfsurrl7v+4JOR3grv+RyG0MtE/OS0sm2f8CvjZXFAJmUpXg=
  app: findplaceonline
