language: node_js
node_js:
- stable
before_script:
- npm install
script:
- npm test
after_success:
deploy:
  provider: heroku
  api_key:
    secure: GTKPu6nrvBwsFw5K/flrq9Zw5c25CGJyvhgGPM6W/2KB9WxG2NaRxsQViRyKYan7ylqiyNfgmKv8MnJYTHvnXZxG5WuLJeU2G/IIYXmpMaolSzauRoHN6V8yclPNLPvQ/h78jKFC2WUoGOC53qt2NKaj+yJNPv/sjkThUIQ79yxxmeq1LlicX8xMv1c9u0QlFZP+nR8lZF7oNVGy6wnaqXLFZLbqwUmKZpS+Ti0evtG1p3BydsREFHVGMx/37MMk1JXl8Ij1fQ1sNeCyOp4FLEmFCzuzVruYzY7Y/MsyPKmBbTnxO3WR/tMymh6LPrf737QLso5o3eUofrEbC5QEvuLMvBXEdJiDQ0XY/GZ1zk7ULbRWTbnBqdD2v1pj+94hKJua7QR8NsUmO15StX/YIvuvFhkIiBGqeq6iEvfDuP0xyCqeqQ3UPtKttPD7aDLhsIClx2mYLBMb5IkudwP7EGP572pIW+pBgbEhAtb4zOBgMN7JMjkqgwMLVTj+DYOWt69pWZv1AB1QqEgGd3mthlNAjGJKspBGwRWnQD+P5xpUyjzZar97QHPXPT1YTELzmS2PHLYXedrUORqBOgGTFPUvCYvc69oSgBXg0zVkCorhY+hU8zTdFuaCOawCLfVmX4JZkFHIVpq9uBX7TCh9AvzvoT0z5RlRJUHCTAb0zH0=
  app: findplaceonline
